### PR TITLE
Panels with curved outline can't be pulled

### LINKED ISSUE #139: Elements with curved geometry cant be pulled
#### Description:
When pulling curved panels and openings the geometry is not converted from RFEM. The following issues arise:
- Curved panels dont get pulled
- Panels with curved openings dont get pulled.

#### Steps to reproduce:
Run script with attached test files

#### Expected behaviour:
Bars and panels to be successfully replicated after pull

#### Test file(s):
[Test Files here ](https://burohappold-my.sharepoint.com/:f:/g/personal/oliver_stainton_burohappold_com1/EsevGBgJ3M5CrbmA0MAepMwBV0Wqm8DLJ0-6CCpuhnJprQ?e=xfZwwU)

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

Before it was not possible to pull/push panels or openings with a curved outline. It was also not possible to pull bars with sections of type Rectangle, Pipe, Circle or Round when working in the german version of RFEM. 

 Closes #139 #140 

 
139: This PR should enable the user to pull/push panels and openings contanint of either plane polylines (which was also possible previously), arches circles or a combination of polylines and arcs.  

140: It should also be possible to pull bars with sections of type Rectangle, Pipe, Circle or Round when working in the german version of RFEM. 

 ### Test files

[Test File 139](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RFEM_Toolkit/RFEM_Toolkit_Elements%20with%20curved%20geometry%20cant%20be%20pulled.gh?csf=1&web=1&e=YmSIa0)
[Test File 140](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RFEM_Toolkit/Issue%20139_files?csf=1&web=1&e=5w0fLs)

 ### Additional comments
139: Please make sure that your RFEM window is "Blank". The current version is not able to overwrite the RFEM model so you will receive an error message in GH. 
140: When testing for issue 140 it is neccesary to change the language in RFEM to german (see [link](https://www.dlubal.com/zh/downloads-and-information/documents/online-manuals/rfem-5/10/01/12)). 

### Changelog

- Adding functionality to read panels with a circular/arched panels and opening outline. 
- Adding functionality to write panels with a circular/arched panels and opening outline.
- Adding a dictionary to enable the pull of the mentioned cross sections.

### CODE REVIEW

**Review by staintono — DISMISSED** [review]
Using the provided test file panels and openings with curved outlines can be successfully pushed and pulled.

File: RFEM_Adapter/CRUD/Read/Panel.cs [hunk 1]
```diff
@@ -147,22 +147,71 @@ private List<Edge> GetEdgesFromRFEMSurface(rf.Surface surface)
...
+
+                    edgeList.Add(new Edge {Curve= circle});
+
+
+                }
+                
+
+                else
+                {
+                    Engine.Base.Compute.RecordError("Import of the chosen panel shape is currently not supported!");
```
Comment (MartinHenriksen) [inline RFEM_Adapter/CRUD/Read/Panel.cs:213]: we should add description of type, so user knows what is not supported

File: RFEM_Adapter/CRUD/Read/Panel.cs [hunk 2]
```diff
@@ -147,22 +147,71 @@ private List<Edge> GetEdgesFromRFEMSurface(rf.Surface surface)
...
             List<int> boundaryLineIds = GetIdListFromString(boundaryString);
 
-
             foreach (int edgeId in boundaryLineIds)
             {
-                List<oM.Geometry.Point> ptsInEdge = new List<oM.Geometry.Point>();
-                string nodeIdString = modelData.GetLine(edgeId, rf.ItemAt.AtNo).GetData().NodeList;
-                List<int> nodeIds = GetIdListFromString(nodeIdString);
+                //Polyline
+                if (modelData.GetLine(edgeId, rf.ItemAt.AtNo).GetData().Type.Equals(rf.LineType.PolylineType))
```
Comment (MartinHenriksen) [inline RFEM_Adapter/CRUD/Read/Panel.cs:155]: each of these if-statements makes 3 COM-calls to get the same line data. We could refactor to make this cleaner and faster

File: RFEM_Adapter/CRUD/Read/Panel.cs [hunk 3]
```diff
@@ -216,17 +265,66 @@ private List<ICurve> GetEdgesAsCurveFromOpenings(rf.Opening openings)
 
             foreach (int edgeId in boundaryLineIds)
             {
-                List<oM.Geometry.Point> ptsInEdge = new List<oM.Geometry.Point>();
-                string nodeIdString = modelData.GetLine(edgeId, rf.ItemAt.AtNo).GetData().NodeList;
-                List<int> nodeIds = GetIdListFromString(nodeIdString);
 
-                foreach (int ptId in nodeIds)
+
```
Comment (MartinHenriksen) [inline RFEM_Adapter/CRUD/Read/Panel.cs:269]: this whole method is almost a straight copy of 'GetEdgesFromRFEMSurface'. This might be able to be refactored to a single method that takes 'boundaryString' as argument

**Review by MartinHenriksen — CHANGES_REQUESTED** [review]
Functionality works, but some code improvements can be done

File: RFEM_Adapter/CRUD/Create/Panel.cs [hunk 4]
```diff
@@ -95,98 +83,206 @@ private bool CreateCollection(IEnumerable<Panel> panels)
...
-
                 }
             }
 
             return true;
         }
 
-
-        public List<string> GenerateOutlineNodeList(List<Edge> edgeList)
+        public List<rf.Line> GenerateOutlineLines(List<Edge> edgeList)
```
[the remark this answers is not in the document]
Comment (Arne-Martensen) [reply RFEM_Adapter/CRUD/Create/Panel.cs:109]: Method has been canged to private.

File: RFEM_Adapter/CRUD/Read/Panel.cs (hunk 2 above)
Comment (Arne-Martensen) [reply RFEM_Adapter/CRUD/Read/Panel.cs:155]: The 3 COM-calls in the if-statements have been reduced to a single one.

File: RFEM_Adapter/CRUD/Read/Panel.cs (hunk 1 above)
Comment (Arne-Martensen) [reply RFEM_Adapter/CRUD/Read/Panel.cs:213]: The description of the edge type is added to the error message.

File: RFEM_Adapter/CRUD/Read/Panel.cs (hunk 3 above)
Comment (Arne-Martensen) [reply RFEM_Adapter/CRUD/Read/Panel.cs:269]: The two methods 'GetEdgesAsCurveFromOpenings' and 'GetEdgesFromRFEMSurface' have been replaced by the function 'GetBoundaryEdges'.

**Review by staintono — APPROVED** [review]
Using the provided test file panels and openings with curved outlines can be successfully pushed and pulled. 

With RFEM set to German bars can now be pulled successfully as explicit sections

**Review by MartinHenriksen — APPROVED** [review]
Code reviewed and looks good. no change in functionality, all still works as expected.

**Comment by MartinHenriksen** [comment]
@BHoMBot check ready-to-merge

**Comment by MartinHenriksen** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 7615384749
