### PR TITLE
Fixing Incorrect Material Push/Pull 

### LINKED ISSUE #118: Bars wont Push with existing sections in the model
#### Description:

When trying to push bars into an existing RFEM Model (Model already contains sections and materials), an error occurs that causes the bars not to be pushed. Presumably this is due to not being able to pull the sections already existing in the model. this error is not produced when pushing to a newly created model. 
image

#### Steps to reproduce:

Push bar geometry into a RFEM model with already defined sections that cannot be pulled into the BHoM.

#### Expected behaviour:

Be able to push bars into an already existing model-

#### Test file(s):

https://burohappold-my.sharepoint.com/:f:/g/personal/oliver_stainton_burohappold_com1/EvBN3lxMwLFMhBkj3UosqdQBcL2RSBjWlhgkem5rqs1wCA?e=dOjf31

### LINKED ISSUE #142: Materials not identified correctly in Push/Pull
When Pushing and Pulling elements the applied materials are not recognised by RFEM when pushing, and by BHoM when pulling.

#### Description:

When pushing elements the default material type of steel is assigned, with the name just being applied as text in RFEM, and not being associated with the relevant material.

When pulling elements, the material type is recognised correctly (Steel, concrete etc.) however the material grade is not recognised. The material pulled is pulled empty without any parameters.

#### Steps to reproduce:

Push and pull using the test files below. 

#### Expected behaviour:
The materials should be fully recognised by both RFEM and BHoM.

#### Test file(s):
[Test Files](https://burohappold-my.sharepoint.com/:f:/g/personal/oliver_stainton_burohappold_com1/EjwRHRb0Z5JElIlv3yNP1aUBQoJyJ1DHAq7OP2Ake2RgYw?e=aU3jgI)

### PR DESCRIPTION
**Pull request by Arne-Martensen**
### Issues addressed by this PR

**Issue 142:**
Push: When Pushing elements into RFEM the type of material is not transfered/generated correctly. The created material that is pused into RFEM does have the same material parameter as the ones defined in the BHoM but is per default alsway assigned as steel. Only the name said concrete (e.g., c x/y). 

Pull: When pulling elements, the material type is recognised correctly (Steel, concrete etc.) however the material grade is not recognised. The material pulled is pulled empty without any parameters

**Expected behaviour - Issue 142:** The materials should be fully recognised by both RFEM and BHoM

**Issue 118:** 
When trying to push bars into an existing RFEM Model (Model already contains sections and materials), an error occurs that causes the bars not to be pushed. Presumably this is due to not being able to pull the sections already existing in the model. this error is not produced when pushing to a newly created model.

**Expected behaviour - Issue 118:** Bars should be pushed into RFEM regardless of the number of Material aready defined in the current RFEM file.  

 Closes #142 
 Closes #118 

 
**Issue 142:** 
Main problem was the access to the RFEM material library through the COM interface. Issue has been solved by adding material Information into the materials description and comment. By that the access to the material library were not needed and the necessary material info from the BHoM could be stored. Now all pushed Materials do have a prefix (e.g., STEEL:). The comment does now additionally store information on yielding strength, ultimate strength, cylinder stress or cube stress.

**Issue 118:**
When pushing an element into RFEM previously the material table could cause some errors when not all materials have been enumerated in a gab less series. So as soon as there was an empty row this could have caused an issue. This issue has been solved by iterating over the material list to find a particular material rather than access the material by using a counter. 
Another issue that was causing trouble was the presence of cross sections without any material attached to them. Now all material without any material automatically gets the material 1 of the material table now.

 ### Test files

[Link to test files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RFEM_Toolkit/Issue%23118And%23142?csf=1&web=1&e=7zaRHK)

 ### Changelog

- Push Material with correct type and parameters and type
- Pull Material with correct material parameters and type
- Enable push of bars into non empty RFEM project

### CODE REVIEW

**Review by staintono — COMMENTED** [review]
Pushed Materials are turning up as a Steel material in RFEM. Pulled Materials do not have the material name assigned to the material, however it is being pulled as a Concrete material.

**Comment by Arne-Martensen** [comment]
> 

Not sure why but this PR should still have been a draf. Sorry for the confusion. Still working on it but should be fixed soon.

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Review by staintono — DISMISSED** [review]
Using the provided test scripts materials can be pushed and pulled while being correctly identified

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

**Comment by Arne-Martensen** [comment]
@BHoMBot check required

**Comment by Arne-Martensen** [comment]
@BHoMBot check required

**Comment by Arne-Martensen** [comment]
@BHoMBot check required

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check required

**Comment by Arne-Martensen** [comment]
@BHoMBot check compliance

**Comment by Arne-Martensen** [comment]
@BHoMBot check required

**Comment by Arne-Martensen** [comment]
@BHoMBot check required

**Review by staintono — APPROVED** [review]
Using the provided test scripts materials can be pushed and pulled while being correctly identified

**Comment by Arne-Martensen** [comment]
@BHoMBot check ready-to-merge

File: RFEM_Adapter/CRUD/Create/Material.cs [hunk 1]
```diff
@@ -40,21 +40,28 @@ public partial class RFEMAdapter
...
-                for(int i=0;i< matList.Count();i++)
+                for (int i = 0; i < matList.Count(); i++)
                 {
                     idNum = GetAdapterId<int>(matList[i]);// NextId(matList[i].GetType()));
                     rfMaterials[i] = matList[i].ToRFEM(idNum);
 
-                    modelData.SetMaterial(rfMaterials[i]);
+                    List<rf.Material> alreadyExistingMaterialsOFEqualType = modelData.GetMaterials().ToList().FindAll(m => m.Description.Equals(rfMaterials[i].Description));
+
+                    bool materialAlreadyInDict = m_materialDict.Any(m => (m.Value.Name.Equals(" " + matList[i].Name)) || (m.Value.Name.Equals(matList[i].Name)));
```
Comment (FraserGreenroyd) [inline RFEM_Adapter/CRUD/Create/Material.cs:56]: For future use, you could do something like `m.Value.Name.Trim().Equals(matList[i].Name)` - the `Trim()` function would remove any whitespace at the start or end of the name which would remove the need to do `.Value.Name.Equals(" " + matList[i].Name)`
